### ISSUE TITLE
Delete scrapped monitoring docs to prevent data bloat 

### ISSUE THREAD

**Issue by eljhkrr** [medic/cht-app-monitoring-data-ingest#77]
Proposed period for maintaining records is 6 months as we're unlikely to act on older data

**Comment by yrimal** [comment]
If we delete the data, it means we can't reuse the informaiton already available for other purposes. If you want to ensure that reporting is not impacted because of the huge dataset, we can drop the old data in historical tables and keep reporting data for 6 months only. [Here's](https://github.com/medic/medic-projects/tree/master/middleware/postgresql/dwh_impact/historical) how we are doing that for impact monitoring. 

This way, we can keep the scraped data for longer term, yet keep current reporting data small and fast.

**Comment by eljhkrr** [comment]
Thanks @yrimal, added as agenda item for upcoming meeting

**Comment by derickl** [comment]
If the target table is well formed, you wouldn't have an issue with a proper indexing strategy

**Comment by yrimal** [comment]
>Should we just ignore this issue for now?

I agree, this sounds like a nominal data.
